#site settings 
title: Suma estudiantil 
author: Luis Gerardo Parra Cayetano
 name: Luis Gerardo Parra Cayetano
 email: gerardoparracayetano@gmail.com
description: Un acercamiento a formas didacticas de la filosofía medieval; la suma.
